openapi: 3.0.2
info:
  title: Base-Service
  description: "Base-Service"
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url: https://localhost:8080
paths:
  /base:
    get:
      tags:
        - BASE
      summary: BASE
      operationId: getBase
      responses:
        200:
          description: good Base
        404:
          description: Base not found
        500:
          description: its not good bro
components:
  schemas:
    Base:
      type: object
      properties:
        id:
          type: integer
          format: int64
        label:
          type: string
